### ISSUE TITLE
Version control conflict markers in files

### ISSUE THREAD

**Issue by davipatti** [seroanalytics/serosolver#48]
I've just tried to install serosolver, but four files (`R/mcmc.R`, `R/RcppExports.R`, `src/boosting_functions_fast.cpp` and `src/boosting_functions_fast.h` contain merge conflict markers which obviously prevent compilation..!

**Comment by davipatti** [comment]
(p.s. Hi @jameshay218 - this is David Pattinson from Cambridge. Hope you're well! I was poking around and came across this package which looks great.)

**Comment by jameshay218** [comment]
Hi David, good to hear from you! I see that David Hodgson has been pushing changes to the master branch(a David-centric interest apparently). I'll find out what he's been up to.

I'd suggest trying to install from the last commit from my, which is June 2020 I believe (commit 8270dc623ed333060388aef4ecf870d16990ed98). That shouldn't have any merge conflicts, but let me know if there are still issues.

**Comment by dchodge** [comment]
Hello David P, This was my fault; I've been adding some new features to serosovler this week. Should all be working now! Let me know if there are any more issues
